spring:
  application:
    name: pokeRogueBot
  datasource:
    url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        show-sql: true

ocr:
  language: deu
  datapath: /opt/homebrew/Cellar/tesseract/5.3.4_1/share/tessdata
  jnaLibraryPath: /opt/homebrew/opt/tesseract/lib/

browser:
  closeOnExit: true
  defaultWaitTimeAfterAction: 500
  waitTimeForRenderAfterNavigation: 5000
  retry:
    maxAttempts: 5
    backoffPeriod: 1000


handler:
  login:
    retryCount: 11
    retryDelayMs: 5000
    delayForFirstCheckMs: 5000
    loginFormSearchWords:
      - "Benutzername"
      - "Passwort"
      - "Melde"
      - "dich"
      - "an"
      - "oder"
      - "erstelle"
      - "einen"
      - "Account"
      - "zum"
      - "starten"
      - "Keine"
      - "Email"
      - "n√∂tig"
    loginFormOcrConfidenceThreshhold: 0.7

logging:
  level:
    ROOT: INFO
    com.sfh: DEBUG